routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '', 'as' => 'home'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
});

Route::resource('user', 'UsersController');
Route::resource('category', 'CategoriesController');
Route::resource('team', 'TeamsController');

Route::resource('status', 'StatusesController');
Route::resource('detail', 'DetailsController');

app/Models/User.php
<?php

namespace scoutsys\Models;

use scoutsys\Models\Team;
use scoutsys\Models\Status;
use scoutsys\Models\Detail;
use scoutsys\Models\Category;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements Transformable
{
    use Notifiable;
    use SoftDeletes;
    use TransformableTrait;

    protected $dates = ['deleted_at'];

    protected $fillable = [
        'name',
        'email',
        'password',
        'birth',
        'nickname',
        'permission'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = env('PASSWORD_HASH') ? bcrypt($value) : $value;
    }

    public function statuses()
    {
        return $this->morphToMany(Status::class, 'statusable');
    }

    public function details()
    {
        return $this->morphToMany(Detail::class, 'detailable');
    }

    public function categories()
    {
        return $this->morphToMany(Category::class, 'categoryable');
    }

    public function team()
    {
        return $this->belongsTo(Team::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace scoutsys\Http\Controllers;

use scoutsys\Services\UserService;
use scoutsys\Validators\UserValidator;
use scoutsys\Interfaces\UserRepository;
use scoutsys\Interfaces\StatusRepository;
use scoutsys\Interfaces\CategoryRepository;
use scoutsys\Http\Requests\UserCreateRequest;
use scoutsys\Http\Requests\UserUpdateRequest;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;

class UsersController extends Controller
{
    protected $repository;
    protected $categoryRepository;
    protected $statusRepository;
    protected $validator;
    protected $userService;

    public function __construct(UserRepository $repository, UserValidator $validator, UserService $userService, CategoryRepository $categoryRepository, StatusRepository $statusRepository)
    {
        $this->middleware('auth');
        $this->repository = $repository;
        $this->categoryRepository = $categoryRepository;
        $this->statusRepository = $statusRepository;
        $this->validator  = $validator;
        $this->userService = $userService;
    }

    public function index()
    {
        $users = $this->repository->all();
        $categories = $this->categoryRepository->pluck('description', 'id');
        $status = $this->statusRepository->pluck('description', 'id');

        // dd($users);

        return view('users.index', compact('users', 'categories', 'status'));
    }

    public function create()
    {
        $categories = $this->categoryRepository->pluck('description', 'id');
        $status = $this->statusRepository->pluck('description', 'id');
        
        return view('users.create', compact('categories', 'status'));
    }

    public function store(UserCreateRequest $request)
    {
        $data = $request->all();

        // dd($data);

        try {
            $this->userService->store($data);
        } catch (ValidatorException $e) {
            throw $e->getMessage();
        }

        return redirect()->route('user.index');
    }

    public function show($id)
    {
        $user = $this->repository->find($id);

        return view('users.show', compact('user'));
    }

    public function edit($id)
    {
        $user = $this->repository->find($id);
        $categories = $this->categoryRepository->pluck('description', 'id');
        $status = $this->statusRepository->pluck('description', 'id');                

        return view('users.edit', compact('user', 'categories', 'status'));
    }

    public function update(UserUpdateRequest $request, $id)
    {
        $data = $request->all();

        // dd($data);

        try {
            $this->userService->update($data, $id);
        } catch (ValidatorException $e) {
            throw $e->getMessage();
        }

        return redirect()->route('user.index');
    }

    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        return redirect()->route('user.index');
    }
}

resources/views/users/_form.blade.php
<div class="form-group row">
    {!! Form::label('name', 'Nome', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('name', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('birth', 'Data de Nascimento', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::date('birth', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('email', 'E-mail', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('email', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('nickname', 'Apelido', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('nickname', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('category_id', 'Categoria', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::select('category_id', $categories, null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('permission', 'Permissão', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::select('permission', ['app.admin' => 'Administrador', 'app.coach' => 'Treinador', 'app.player' => 'Jogador'], null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

<div class="form-group row">
    {!! Form::label('status_id', 'Status', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::select('status_id', $status, null, ['class' => 'form-control']) !!}
    </div>
</div>

resources/views/users/create.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('user.create'))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">

            {!! Form::open(['route' => 'user.store']) !!}

            @include('users._form')

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                        <a href="{{ route('user.index') }}" class="btn btn-default">Cancelar</a>
                    </div>
                </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>
@stop

resources/views/users/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('user.edit', $user))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!! Form::model($user, ['route' => ['user.update', $user->id], 'method' => 'PATCH']) !!}
            
            @include('users._form')

            <div class="form-group row">
                <div class="col-md-6 offset-md-4">
                    {!! Form::submit('Alterar', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('user.index') }}" class="btn btn-default">Cancelar</a>
                </div>
            </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@section('name')
    
@endsection

resources/views/users/index.blade.php
@extends('layouts.layout') 

@section('breadcrumbs', Breadcrumbs::render('user.index'))

@section('content')

<a class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Cadastrar usuário" role="button" href="{{ route('user.create') }}">
    Cadastrar usuário <i class="fas fa-plus-circle"></i>
</a>
<div class="container-fluid">
    <div class="row justify-content-center">
        @include('layouts.forms.confirmation-modal')
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Data de Nascimento</th>
                    <th class="text-center">E-mail</th>
                    <th class="text-center">Categoria</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">Permissão</th>
                    <th class="text-center">Opções</th>
                </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                <tr>
                    <th scope="row" class="text-center">{{ $user->id }}</th>
                    <td>{{ $user->name }}</td>
                    <td class="text-center">{{ date('d/m/Y', strtotime($user->birth)) }}</td>
                    <td>{{ $user->email }}</td>
                    <td class="text-center">
                        @foreach ($user->categories as $category)
                        <a href="{{ route('category.show', $category->id) }}">
                            {{ $category->description }}
                        </a>
                        @endforeach
                    </td>
                    <td class="text-center">
                        @foreach ($user->statuses as $status)
                        <a href="{{ route('status.show', $status->id) }}">
                            {{ $status->description }}
                        </a>
                        @endforeach
                    </td>
                    <td class="text-center">{{ $user->permission }}</td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-outline-info" data-toggle="tooltip" data-placement="top" title="Visualizar usuário" role="button" href="{{ route('user.show', $user->id) }}">
                            <i class="fa fa-info-circle" aria-hidden="true"></i>
                        </a>
                        <a class="btn btn-sm btn-outline-warning" data-toggle="tooltip" data-placement="top" title="Alterar usuário" role="button" href="{{ route('user.edit', $user->id) }}">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <button class="btn btn-sm btn-outline-danger load-confirmation-modal" data-toggle="tooltip" data-placement="top" title="Excluir usuário" role="button" data-url="{{ route('user.destroy', $user->id) }}" data-type="Usuário" data-name="{{ $user->name }}" data-target="#confirmation-modal" data-toggle="modal">
                            <i class="fas fa-trash"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
        </table>
    </div>
</div>
@endsection
 
@section('after-script')
<script src="{{ asset('js/confirmation-modal.js') }}"></script>
<script src="{{ asset('js/tooltip.js') }}"></script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.layout') 

@section('breadcrumbs', Breadcrumbs::render('user.show', $user))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Nome</th>
                    <th class="text-center">Data de Nascimento</th>
                    <th class="text-center">E-mail</th>
                    <th class="text-center">Apelido</th>
                    <th class="text-center">Permissão</th>
                    <th class="text-center">Opções</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="text-center">{{ $user->id }}</th>
                    <td>{{ $user->name }}</td>
                    <td class="text-center">{{ date('d/m/Y', strtotime($user->birth)) }}</td>
                    <td class="text-center">{{ $user->email }}</td>
                    <td class="text-center">{{ $user->nickname }}</td>
                    <td class="text-center">{{ $user->permission }}</td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-outline-info" data-toggle="tooltip" data-placement="top" title="Dados cadastrais do usuário" role="button" href="{{ route('detail.show', $user->id) }}">
                            <i class="fas fa-address-card"></i>
                        </a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@if (!empty($user->details->toArray()))

@yield('details-content')

@endif

@endsection