routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '', 'as' => 'home'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
});

Route::resource('user', 'UsersController');
Route::resource('category', 'CategoriesController');
Route::resource('team', 'TeamsController');

Route::resource('status', 'StatusesController');
Route::resource('detail', 'DetailsController');

app/Models/Status.php
<?php

namespace scoutsys\Models;

use scoutsys\Models\Team;
use scoutsys\Models\User;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Status.
 *
 * @package namespace scoutsys\Models;
 */
class Status extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['description'];

    public function statusable()
    {
        return $this->morphTo();
    }

    public function users()
    {
        return $this->morphedByMany(User::class, 'statusable');
    }

    public function teams()
    {
        return $this->morphedByMany(Team::class, 'statusable');
    }
}

resources/views/status/_form.blade.php
<div class="form-group row">
    {!! Form::label('description', 'Descrição', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('description', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

resources/views/status/create.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('status.create'))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!! Form::open(['route' => 'status.store']) !!}
            
            @include('status._form')
            
            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('status.index') }}" class="btn btn-default">Cancelar</a>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/status/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('status.edit', $status))

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Alterar Status
                </div>

                <div class="card-body">
                    {!! Form::model($status, ['route' => ['status.update', $status->id], 'method' => 'PATCH']) !!}

                        @include('status._form')

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                {!! Form::submit('Alterar', ['class' => 'btn btn-primary']) !!}
                                <a href="{{ route('status.index') }}" class="btn btn-default">Cancelar</a>
                            </div>
                        </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/status/index.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('status.index'))

@section('content')
<a class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Cadastrar status" role="button" href="{{ route('status.create') }}">
    Cadastrar status <i class="fas fa-plus-circle"></i>
</a>
<div class="container-fluid">
    <div class="row justify-content-center">
        @include('layouts.forms.confirmation-modal')
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Descrição</th>
                    <th class="text-center">Opções</th>
                </tr>
            </thead>
            <tbody>
                @foreach($status as $status)
                <tr>
                    <th scope="row" class="text-center">{{ $status->id }}</th>
                    <td class="text-center">{{ $status->description }}</td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-outline-info" data-toggle="tooltip" data-placement="top" title="Visualizar status" role="button" href="{{ route('status.show', $status->id) }}">
                            <i class="fas fa-info-circle"></i>
                        </a>
                        <a class="btn btn-sm btn-outline-warning" data-toggle="tooltip" data-placement="top" title="Alterar status" role="button" href="{{ route('status.edit', $status->id) }}">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <button class="btn btn-sm btn-outline-danger load-confirmation-modal" data-toggle="tooltip" data-placement="top" title="Excluir status" role="button" data-url="{{ route('status.destroy', $status->id) }}" data-type="Status" data-name="{{ $status->description }}" data-target="#confirmation-modal" data-toggle="modal">
                            <i class="fas fa-trash"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
        </table>
    </div>
</div>
@endsection

@section('after-script')
<script src="{{ asset('js/confirmation-modal.js') }}"></script>
<script src="{{ asset('js/tooltip.js') }}"></script>
@endsection

resources/views/status/show.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('status.show', $status))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th>Descrição</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="text-center">{{ $status->id }}</th>
                    <td>{{ $status->description }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection