routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '', 'as' => 'home'], function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index');
});

Route::resource('user', 'UsersController');
Route::resource('category', 'CategoriesController');
Route::resource('team', 'TeamsController');

Route::resource('status', 'StatusesController');
Route::resource('detail', 'DetailsController');

app/Models/Category.php
<?php

namespace scoutsys\Models;

use scoutsys\Models\Team;
use scoutsys\Models\User;
use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Category.
 *
 * @package namespace scoutsys\Models;
 */
class Category extends Model implements Transformable
{
    use TransformableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['description'];

    // public function teams()
    // {
    //     return $this->hasMany(Team::class);
    // }

    // public function users()
    // {
    //     return $this->hasMany(User::class);
    // }

    public function categoryable()
    {
        return $this->morphTo();
    }

    public function users()
    {
        return $this->morphedByMany(User::class, 'categoryable');
    }

    public function teams()
    {
        return $this->morphedByMany(Team::class, 'categoryable');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace scoutsys\Http\Controllers;

use Illuminate\Http\Request;

use scoutsys\Http\Requests;
use Prettus\Validator\Contracts\ValidatorInterface;
use Prettus\Validator\Exceptions\ValidatorException;
use scoutsys\Http\Requests\CategoryCreateRequest;
use scoutsys\Http\Requests\CategoryUpdateRequest;
use scoutsys\Interfaces\CategoryRepository;
use scoutsys\Validators\CategoryValidator;

/**
 * Class CategoriesController.
 *
 * @package namespace scoutsys\Http\Controllers;
 */
class CategoriesController extends Controller
{
    /**
     * @var CategoryRepository
     */
    protected $repository;

    /**
     * @var CategoryValidator
     */
    protected $validator;

    /**
     * CategoriesController constructor.
     *
     * @param CategoryRepository $repository
     * @param CategoryValidator $validator
     */
    public function __construct(CategoryRepository $repository, CategoryValidator $validator)
    {
        $this->middleware('auth');
        $this->repository = $repository;
        $this->validator  = $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->repository->pushCriteria(app('Prettus\Repository\Criteria\RequestCriteria'));
        $categories = $this->repository->all();

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $categories,
            ]);
        }

        return view('categories.index', compact('categories'));
    }

    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CategoryCreateRequest $request
     *
     * @return \Illuminate\Http\Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function store(CategoryCreateRequest $request)
    {
        try {
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_CREATE);

            $category = $this->repository->create($request->all());

            return redirect()->route('category.index');
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->repository->find($id);

        if (request()->wantsJson()) {
            return response()->json([
                'data' => $category,
            ]);
        }

        return view('categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->repository->find($id);

        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CategoryUpdateRequest $request
     * @param  string            $id
     *
     * @return Response
     *
     * @throws \Prettus\Validator\Exceptions\ValidatorException
     */
    public function update(CategoryUpdateRequest $request, $id)
    {
        try {
            $this->validator->with($request->all())->passesOrFail(ValidatorInterface::RULE_UPDATE);

            $category = $this->repository->update($request->all(), $id);

            $response = [
                'message' => 'Category updated.',
                'data'    => $category->toArray(),
            ];

            if ($request->wantsJson()) {
                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = $this->repository->delete($id);

        if (request()->wantsJson()) {
            return response()->json([
                'message' => 'Category deleted.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Category deleted.');
    }
}

resources/views/categories/_form.blade.php
<div class="form-group row">
    {!! Form::label('description', 'Descrição', ['class' => 'col-md-4 col-form-label text-md-right']) !!}
    <div class="col-md-6">
        {!! Form::text('description', null, ['class' => 'form-control', 'required', 'autofocus']) !!}
    </div>
</div>

resources/views/categories/create.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('category.create'))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            {!! Form::open(['route' => 'category.store']) !!}
            
            @include('categories._form')
            
            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                    <a href="{{ route('category.index') }}" class="btn btn-default">Cancelar</a>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('category.edit', $category))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            
            {!! Form::model($category, ['route' => ['category.update', $category->id], 'method' => 'PATCH']) !!}

                @include('categories._form')

                <div class="form-group row mb-0">
                    <div class="col-md-6 offset-md-4">
                        {!! Form::submit('Alterar', ['class' => 'btn btn-primary']) !!}
                        <a href="{{ route('category.index') }}" class="btn btn-default">Cancelar</a>
                    </div>
                </div>

            {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('category.index'))

@section('content')
<a class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Cadastrar categoria" role="button" href="{{ route('category.create') }}">
    Cadastrar categoria <i class="fas fa-plus-circle"></i>
</a>
<div class="container-fluid">
    <div class="row justify-content-center">
        @include('layouts.forms.confirmation-modal')
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Descrição</th>
                    <th class="text-center"># de Treinadores</th>
                    <th class="text-center"># de Jogadores</th>
                    <th class="text-center"># de Equipes</th>
                    <th class="text-center">Opções</th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                <tr>
                    <th scope="row" class="text-center">{{ $category->id }}</th>
                    <td>{{ $category->description }}</td>
                    <td class="text-center">{{ $category->users->where('permission', 'app.coach')->count() }}</td>
                    <td class="text-center">{{ $category->users->where('permission', 'app.player')->count() }}</td>
                    <td class="text-center">{{ $category->teams->count() }}</td>
                    <td class="text-center">
                        <a class="btn btn-sm btn-outline-info" data-toggle="tooltip" data-placement="top" title="Visualizar categoria" role="button" href="{{ route('category.show', $category->id) }}">
                            <i class="fas fa-info-circle"></i>
                        </a>
                        <a class="btn btn-sm btn-outline-warning" data-toggle="tooltip" data-placement="top" title="Alterar categoria" role="button" href="{{ route('category.edit', $category->id) }}">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <button class="btn btn-sm btn-outline-danger load-confirmation-modal" data-toggle="tooltip" data-placement="top" title="Excluir categoria" role="button" data-url="{{ route('category.destroy', $category->id) }}" data-type="Categoria" data-name="{{ $category->description }}" data-target="#confirmation-modal" data-toggle="modal">
                            <i class="fas fa-trash"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
        </table>
    </div>
</div>
@endsection

@section('after-script')
<script src="{{ asset('js/confirmation-modal.js') }}"></script>
<script src="{{ asset('js/tooltip.js') }}"></script>
@endsection

resources/views/categories/show.blade.php
@extends('layouts.layout')

@section('breadcrumbs', Breadcrumbs::render('category.show', $category))

@section('content')
<div class="container-fluid">
    <div class="row justify-content-center">
        <table class="table table-sm">
            <thead class="thead-light">
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Descrição</th>
                    <th class="text-center">Equipes</th>
                    <th class="text-center">Treinadores</th>
                    <th class="text-center">Jogadores</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th class="text-center">{{ $category->id }}</th>
                    <td>{{ $category->description }}</td>
                    <td>
                        @foreach ($category->teams as $team) 
                            <a href="{{ route('team.show', $team->id) }}">{{ $team->name }}</a>
                        @endforeach
                    </td>
                    <td>
                        @foreach ($category->users->where('permission', 'app.coach') as $coach) 
                            <a href="{{ route('user.show', $coach->id) }}">{{ $coach->name }}</a>
                        @endforeach
                    </td>
                    <td>
                        @foreach ($category->users->where('permission', 'app.player') as $player) 
                            <a href="{{ route('user.show', $player->id) }}">{{ $player->name }}</a>
                        @endforeach
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection